app = "singitan-backend"
primary_region = "dbz"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  DATA_DIR = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  source = "sqlite_data"
  destination = "/data"
  initial_size = "1gb"
